FROM node:12.18.3

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app
COPY package*.json ./

RUN npm install
RUN npm install -g gatsby-cli

COPY . .

ENV GATSBY_API_HOST=localhost
RUN npm run-script build

EXPOSE 3000
CMD ["gatsby", "develop"]