services:
  redis_migration:
    build:
      context: ./data_pipeline
      dockerfile: Dockerfile

  ui:
    container_name: ui
    build: 
      context: .
      dockerfile: Dockerfile.dev
      network: "host"
    ports:
      - "8000:8000"
