version: "3.8"
services:
  redis_migration:
    build:
      context: ./data_pipeline
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redislabs/rejson:latest
    container_name: redis
    ports:
      - "6379:6379"

  api:
    build:
      context: ./redis_api
      dockerfile: Dockerfile.local
    container_name: api
    environment:
      - REDIS_HOST=redis
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - redis_migration

  ui:
    container_name: ui
    build: 
      context: ./frontend
      dockerfile: frontend/Dockerfile.local
      network: "host"
    working_dir: /app
    environment:
      - GATSBY_API_HOST=api:5000
    command: ./entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules/
    depends_on:
      - api
