version: '3'
services:
  redis_migration:
    build:
      context: ./data_pipeline
      dockerfile: Dockerfile

  ui:
    container_name: ui
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
