FROM node:14 as builder

WORKDIR /srv

COPY package.json yarn.lock ./
RUN npm install --legacy-peer-deps
RUN npm config set unsafe-perm true
RUN npm install -g gatsby-cli
COPY . .
ENTRYPOINT [ "sh", "./entrypoint.sh" ]
