FROM python:3.8

ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=.
ENV FLASK_APP=api
ENV FLASK_RUN_HOST=0.0.0.0

WORKDIR /srv

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

EXPOSE 5000

CMD ["python", "-m", "flask", "run"]
