module.exports = {
  ContributorCodes: {
    IND: "Individual",
    COM: "Committee",
    OTH: "Other",
    PTY: "Political party",
    SCC: "Small Contributor Committee",
  },
  ExpenditureCodes: {
    CMP: "Campaign paraphernalia/misc",
    CNS: "Campaign consultants",
    CTB: "Contribution",
    CVC: "Civic donations",
    FIL: "Candidate filing/ballot fees",
    FND: "Fundraising events",
    IND: "Independent expenditure supporting/opposing others",
    LEG: "Legal defense",
    LIT: "Campaign literature and mailings",
    MBR: "Member communications",
    MTG: "Meetings and appearances",
    OFC: "Office expenses",
    PET: "Petition circulating",
    PHO: "Phone banks",
    POL: "Polling and survey research",
    POS: "Postage, delivery and messenger services",
    PRO: "Professional services (legal, accounting)",
    PRT: "Print ads",
    RAD: "Radio airtime and production costs",
    RFD: "Returned contributions",
    SAL: "Campaign workers’ salaries",
    TEL: "TV or cable airtime and production costs",
    TRC: "Candidate travel, lodging, and meals",
    TRS: "Staff/spouse travel, lodging, and meals",
    TSF: "Transfer between committees of the same candidate/sponsor",
    VOT: "Voter registration",
    WEB: "Information technology costs (internet, e-mail)",
  },
}
